Translate gene
labgem/PPanGGOLiN pull request #205
Opened 2024-03-28 16:57 UTC by jpjarnoux

Add the option to write the translated sequence of all genes in the pangenome.

2024-04-23 15:36 UTC, jpjarnoux commented
MMseqs2 create db must be forced in mode 1. So in `translate_genes` we must force the mode.

2024-06-04 12:16 UTC, jpjarnoux commented on ppanggolin/formats/writeSequences.py
> +    onereq.add_argument("--genes_prot", required=False, type=filter_values,
I go with proteins

2024-06-05 09:11 UTC, jpjarnoux commented on ppanggolin/formats/writeSequences.py
> +def translate_genes(sequences: TextIO, tmpdir: Path, threads: int = 1, code: int = 11) -> Path:
genetic_code is still used in writeMSA.py. I suggest not touching this one for now and making the change in another PR.

2024-06-06 09:23 UTC, JeanMainguy requested changes

2024-06-06 09:23 UTC, JeanMainguy commented on ppanggolin/projection/projection.py
> +                                                                       is_input_slf=False, cpu=cpu, no_defrag=no_defrag,
is_input_slf should be set to True as the sequence are written by us

2024-06-06 09:23 UTC, JeanMainguy commented on ppanggolin/projection/projection.py
> +                                                                       is_input_seq_nt=True, is_input_slf=False,
same here

2024-06-06 09:23 UTC, JeanMainguy commented on ppanggolin/cluster/cluster.py
> +    seqdb = translate_genes(sequences, 'aa_db', tmpdir, cpu, True, code)
It would be nicer to add the parameter name here. Especially the True, we don't know what it refers to...

2024-06-06 09:23 UTC, JeanMainguy commented on ppanggolin/formats/writeSequences.py
> +    translate_db = translate_genes(pangenome_sequences, 'aa_db', tmpdir, threads, True, code)
Add param names for better code understanding

2024-06-06 09:23 UTC, JeanMainguy commented on ppanggolin/formats/writeSequences.py
> +    optional.add_argument("--threads", required=False, default=1, type=int, help="Number of available threads")
Use cpu instead of threads for code homogeneity?

2024-06-10 11:18 UTC, JeanMainguy approved these changes

2024-06-10 11:18 UTC, JeanMainguy commented on pyproject.toml
> +[tool.pytest.ini_options]
does it make sense to add that in the toml?

2024-06-10 18:31 UTC, merged